land/urls.py
from django.conf.urls import url
from land import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create-account/$', views.create_account, name='create_account'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^land/register/$', views.register_land, name='register_land'),
    url(r'^land/display/$', views.display_lands, name='display_lands'),
    url(r'^land/display/(?P<pk>[0-9])/$', views.land_detail, name='land_details'),
    url(r'^land/payment/(?P<pk>[0-9])/$', views.buy_land, name='buy_land'),
    url(r'^notifications/$', views.get_notification, name='notification'),
    url(r'^bought-lands/$', views.show_bought_land, name='lands_bought'),
    url(r'^transfer-land/(?P<pk>[0-9])/$', views.transfer_bought_land, name='transfer_land'),
    url(r'^transfer/(?P<land_id>[0-9])/$', views.transfer_land, name='transfer'),
    url(r'^my-land/$', views.my_land, name='my_land'),

]

landsys/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('land.urls', namespace='land'), ),
    url(r'^api/', include('payment.urls', namespace='api'), ),


]

admin.site.site_header = 'Nyeri Land System'

land/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", max_length=100, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', )

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name in ['username', 'password', 'password2']:
            self.fields[field_name].help_text = None


class LandUserProfileForm(forms.Form):
    id_no = forms.CharField(max_length=20, widget=forms.NumberInput(
        attrs={'id': 'id_no_id', 'placeholder': 'Enter National ID No'}
    ))
    ward = forms.CharField(max_length=32, widget=forms.TextInput(
        attrs={'id': 'ward_id', 'placeholder': 'Enter the ward name'}
    ))
    location = forms.CharField(max_length=128, widget=forms.TextInput(
        attrs={'id': 'location_id', 'placeholder': 'Enter Land Location'}
    ))
    district = forms.CharField(max_length=128, widget=forms.TextInput(
        attrs={'id': 'district_id', 'placeholder': 'Enter District Name'}
    ))
    phone_number = forms.CharField(max_length=13, widget=forms.TextInput(
        attrs={'id': 'phone_number_id', 'placeholder': 'Enter your phone number (+2547 xxx xxx)'}
    ))
    address = forms.CharField(max_length=128, widget=forms.TextInput(
        attrs={'id': 'address_id', 'placeholder': 'Enter your physical address'}
    ))


class RegisterLandForm(forms.Form):
    title_deed = forms.CharField(max_length=32, widget=forms.TextInput(
        attrs={'id': 'title_deed_id', 'placeholder': 'Enter Title Deed No', }
    ))
    approximate_size = forms.FloatField(widget=forms.NumberInput(
        attrs={'id': 'land_size_id', 'placeholder': 'Enter The Land Size (Hacters)', }
    ))
    registry_map_sheet_no = forms.CharField(max_length=32, widget=forms.TextInput(
        attrs={'id': 'map_sheet_id', 'placeholder': 'Enter Map-sheet Number)', }
    ))
    district = forms.CharField(max_length=128, widget=forms.TextInput(
        attrs={'id': 'district_id', 'placeholder': 'Enter district', }
    ))
    location = forms.CharField(max_length=128, widget=forms.TextInput(
        attrs={'id': 'location_id', 'placeholder': 'Enter location)', }
    ))
    sale_price = forms.FloatField(widget=forms.NumberInput(
        attrs={'id': 'sale_price_id', 'placeholder': 'Enter Sale Price Ksh (Optional)', }
    ), required=False, )


class LoginForm(forms.Form):
    username = forms.CharField(max_length=32)
    password = forms.CharField(max_length=128, widget=forms.PasswordInput)


class LandPurchaseForm(forms.Form):
    phone_number = forms.CharField(max_length=13, widget=forms.TextInput(
        attrs={'id': 'phone_number_id', 'placeholder': 'Enter Your Phone Number format(+2547 XXX XXX)'}
    ))
    deposit_amount = forms.CharField(max_length=14, widget=forms.NumberInput(
        attrs={'id': 'deposit_amount', }
    ), disabled=True, required=True)


class TransFerLandPaymentForm(forms.Form):
    title_deed = forms.CharField(max_length=32, disabled=True)
    phone_number = forms.CharField(max_length=13, widget=forms.TextInput(
        attrs={'id': 'phone_number_id', 'placeholder': 'Enter Your Phone Number format(+2547 XXX XXX)'}
    ))
    amount = forms.CharField(max_length=14, widget=forms.NumberInput(
        attrs={'id': 'amount_id', }
    ), disabled=True, required=True)


class LandTransferForm(forms.Form):
    first_name = forms.CharField(max_length=128, widget=forms.TextInput(
        attrs={'id': 'first_name_id'}
    ))
    middle_name = forms.CharField(max_length=128, widget=forms.TextInput(
        attrs={'id': 'middle_name_id'}
    ))
    last_name = forms.CharField(max_length=128, widget=forms.TextInput(
        attrs={'id': 'last_name_id'},
    ))
    id_no = forms.CharField(max_length=20, widget=forms.TextInput(
        attrs={'id': 'id_no_id'}
    ))
    district = forms.CharField(max_length=128, widget=forms.TextInput(
        attrs={'id': 'district_id'}
    ))
    location = forms.CharField(max_length=128, widget=forms.TextInput(
        attrs={'id': 'location_id'}
    ))
    sub_location = forms.CharField(max_length=128, widget=forms.TextInput(
        attrs={'id': 'sub_location_id'}
    ))
    transfer_from = forms.CharField(max_length=128, widget=forms.TextInput(
        attrs={'id': 'transfer_from_id'}
    ), disabled=True)
    land_size = forms.FloatField(disabled=True)
    transfer_size = forms.FloatField()

    def clean_transfer_size(self):
        cd = self.cleaned_data
        transfer_size = float(cd['transfer_size'])
        land_size = float(cd['land_size'])
        if transfer_size > land_size:
            raise forms.ValidationError('Insufficient amount of land for this transfer')
        return cd['transfer_size']


class ConfirmCodeForm(forms.Form):
    code = forms.CharField(max_length=20, label="Verification Code",
                           widget=forms.TextInput(
                               attrs={'placeholder': 'Enter Verification Code'}
                           )
                           )

land/views.py
from Crypto.Hash import SHA256
from django.shortcuts import (
    render,
    render_to_response,
    HttpResponse,
    HttpResponseRedirect,
    get_object_or_404,
)
from django.conf import settings

from land.forms import (
    UserRegistrationForm,
    LandUserProfileForm,
    LoginForm,
    RegisterLandForm,
    LandPurchaseForm,
    LandTransferForm,
    ConfirmCodeForm,
    TransFerLandPaymentForm,
)
from land.models import (
    LandUserProfile,
    Land,
    Notification,
    LandSales,
    ChangeLandOwnership,
    LandTransfer,
    LandTransferHistoryLog,

)
from payment.models import (
    Payment,
    LandTransferFee,
    LandTransFerFeePayment,
)
from payment.forms import (
    LandTransFerFeeForm,
)
from land.AfricasTalkingGateway import AfricasTalkingGateway, AfricasTalkingGatewayException
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db import IntegrityError, transaction
from random import randint
from django.conf import settings
from landsys.settings import (
    sandbox_apiKey,
    sandbox_username,
    sandbox_metadata,
    sandbox_currencyCode,
    sandbox_productName,
)


def index(request):
    return render(request, 'land/index.html', {})


# create a user account and land profile as well


def create_account(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = LandUserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password2'])
            user.save()

            # get the data posted in the form
            cd = profile_form.cleaned_data
            id_no = cd['id_no']
            location = cd['location']
            ward = cd['ward']
            address = cd['address']
            district = cd['district']
            phone_no = cd['phone_number']

            profile = LandUserProfile.objects.create(
                user=user,
                id_no=id_no,
                location=location,
                ward=ward,
                district=district,
                address=address,
                phone_number=phone_no
            )
            profile.save()
            message = "Account Created Successfully"
            return render_to_response('land/create_account_success.html',
                                      {'message': message,
                                      })

    else:
        profile_form = LandUserProfileForm()
        user_form = UserRegistrationForm()
    return render(request, 'land/create_account.html',
                  {
                      'user_form': user_form,
                      'profile_form': profile_form,
                  })


# handle the user log in to the system


def user_login(request):
    user = request.user
    next_url = request.GET.get('next', '')
    if user.is_authenticated():
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    request.session['username'] = cd['username']
                    login(request, user)

                    if next_url == '':
                        return HttpResponseRedirect('/')
                    elif next_url:
                        return HttpResponseRedirect(next_url)
            else:

                message = 'Wrong username or password'
                form = LoginForm()
                return render(request, 'land/login.html', {'form': form, 'message': message, })
    else:
        form = LoginForm()
    return render(request, 'land/login.html', {'form': form, })


@login_required(login_url='/login/')
def user_logout(request):
    logout(request)
    try:
        del request.session['username']
        request.session.modified = True
        return render(request, 'land/logout_then_login.html', {})
    except KeyError, e:
        pass
    return render(request, 'land/logout_then_login.html', {})


# register land details

@transaction.atomic()
@login_required(login_url='/login/')
def register_land(request):
    if request.method == 'POST':
        data = request.POST.copy()
        land_form = RegisterLandForm(data)
        # perform checks to ensure all form data is clean
        if land_form.is_valid():
            # form passes the checks now process the data
            cd = land_form.cleaned_data
            title_deed = cd['title_deed']
            approximate_size = cd['approximate_size']
            registry_map_sheet_no = cd['registry_map_sheet_no']
            district = cd['district']
            location = cd['location']
            sale_price = cd['sale_price']
            # create user model instance to link to the actual land owner
            username = request.session.get('username')
            land_owner = get_object_or_404(User, username=username)
            profile = get_object_or_404(LandUserProfile, user=land_owner)
            land = Land.objects.create(
                user=land_owner,
                profile=profile,
                title_deed_no=title_deed,
                registry_map_sheet_no=registry_map_sheet_no,
                approximate_size=approximate_size,
                sale_price=sale_price,
                location=location,
                district=district,
                remaining_size=approximate_size

            )
            land.save()
            error = False
            message = "Your land information has been saved successfully."
            return render_to_response('land/register_land_success.html',
                                      {'message': message,
                                       'error': error,
                                      })

    else:
        land_form = RegisterLandForm()
    return render(request, 'land/register_land.html', {'land_form': land_form, })


# display all the lands that are on sale


def display_lands(request):
    lands = Land.objects.filter(is_onsale=True, )
    return render(request, 'land/lands.html', {'lands': lands, })


# get land details for a given land


def land_detail(request, pk=None):
    land = get_object_or_404(Land, pk=pk)
    return render(request, 'land/land_details.html', {'land': land, })


@transaction.atomic()
def buy_land(request, pk=None):
    land = get_object_or_404(Land, pk=pk)
    sale_price = float(land.sale_price)
    deposit = 0.75 * sale_price
    form_initial = {'deposit_amount': deposit}
    if request.method == 'POST':
        data = request.POST.copy()
        land_purchase_form = LandPurchaseForm(data, initial=form_initial)

        if land_purchase_form.is_valid():
            cd = land_purchase_form.cleaned_data
            buyer_phone_number = cd['phone_number']
            amount = cd['deposit_amount']

            """
             perform m-pesa payment logic here
             for now we bypass the logic and save the data in
             the database later we will implement the payment api
             this is for demo purposes

            """
            # generate a random transaction id
            range_start = 10 ** (10 - 1)
            range_end = (10 ** 10) - 1
            details = "Land Purchase Deposit 0f Ksh {0} For Land On-sale by {1}  {2}".format(
                deposit, land.user.first_name, land.user.last_name
            )
            id_prefix = "HTech"
            transaction_id = randint(range_start, range_end)
            id_hash = SHA256.new(str(transaction_id)).hexdigest()
            t_id = id_prefix + id_hash
            # create a payment model instance here
            username = str(request.user)
            user = get_object_or_404(User, username=username)
            payment = Payment.objects.create(
                user=user,
                transaction_id=t_id,
                phone_number=buyer_phone_number,
                payment_mode="Bank",
                amount=amount,
                details=details,
                status="Success"
            )
            payment.save()
            # record the deposit on the land sales model

            land_owner = land.user.username
            uncleared_amount = sale_price - deposit
            land_sale = LandSales.objects.create(
                land=land,
                owner=land_owner,
                buyer=username,
                deposit_amount=amount,
                uncleared_amount=uncleared_amount,
            )
            land_sale.save()
            # make land not on sale
            land.is_onsale = False
            land.bought = True
            land.save()
            # create a notification
            receiver = land.profile.phone_number
            notification_message = "Dear {0} {1} we are gland to inform you that  " \
                                   "{2}  Has Place a deposit of Ksh {3} " \
                                   "for the land you posted on-sale Contact this client on" \
                                   " {4} ".format(land.user.first_name,
                                                  land.user.last_name,
                                                  request.user,
                                                  deposit,
                                                  buyer_phone_number)
            notification = Notification.objects.create(
                land_id=land,
                sender=buyer_phone_number,
                sent_to=receiver,
                text=notification_message
            )
            notification.save()
            message = 'Deposit made successfully Your Buyer id is {0}'.format(transaction_id)

landsys/templates/land/create_account.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div>
<form action=""  method="POST">
       <fieldset>
            <legend>Profile Details</legend>
            {{ profile_form |crispy }}
        </fieldset>
        <fieldset>
            <legend>User Account Details</legend>

             {{ user_form | crispy }}
        </fieldset>
{% csrf_token %}
<input type="submit" value="Submit" class="btn btn-success btn-raised">

</form>
</div>

{% endblock %}

landsys/templates/land/create_account_success.html
{% extends 'base.html' %}

{% block content %}
<div class="alert alert-success">
<p>{{ message }} <a href="#">click here</a> to login now. </p>
</div>
{% endblock %}

landsys/templates/land/deposit_payment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content">
    <div class="col col-md-12">
    <h6>Make Deposit Payment To complete your request</h6>
    <form action="" method="POST">
        {{ land_purchase_form | crispy }}
        {% csrf_token %}
        <input type="submit" value="mobile checkout" class="btn btn-success btn-raised">
    </form>
    </div>
    </div>
{% endblock %}

landsys/templates/land/index.html
{% extends 'base.html' %}

{% block content %}
<h6>No contents for home page right now</h6>
{% endblock %}

landsys/templates/land/land_details.html
{% extends  'base.html' %}


{% block content %}
<div style="">
<p>Owner: {{ land.user.first_name }}</p>
<p>Location: {{ land.location }}</p>
<p>District: {{ land.district}}</p>
<p>Sale Price: {{ land.sale_price}} Ksh</p>
<p><a href="{% url 'land:buy_land' pk=land.pk %} " class="btn btn-success btn-raised">Send A Buy Request</a> </p>

</div>
{% endblock %}

landsys/templates/land/lands.html
{% extends 'base.html' %}

{% block content %}
    <div class="col col-md-12">
        {% if lands %}
            <table class="table table-responsive">
                <th>Owner</th>
                <th>Land Size</th>
                <th>Location</th>
                <th>Link</th>
                <th></th>
                {% for land in lands %}
                    <tr>
                        <td>{{ land.user.first_name }}&nbsp;&nbsp;{{ land.user.last_name }}</td>
                        <td>{{ land.approximate_size }} acres</td>
                        <td>{{ land.location }}</td>
                        <td><a href="{% url 'land:land_details' pk=land.pk %}" class="btn btn-success ">More Details</a></td>
                        <td><a href="#" class="btn btn-success btn-raised">Contact Owner</a></td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}

             <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4></h4><strong>No land available for sale!</strong></div>
              </div>


        {% endif %}
    </div>
{% endblock %}

landsys/templates/land/lands_bought.html
{% extends 'base.html' %}
{% if lands_bought %}
    {% block content %}
        <div class="col col-md-12">
        {% if lands_bought %}
            <table class="table table-responsive">
                <tr>
                    <td>Title Deed</td>
                    <td>Land Size</td>
                    <td>Amount Deposited</td>
                    <td>Deposited By(Fullname)</td>
                    <td>Deposited By (Account Name)</td>
                    <td>Date Deposited(Ksh)</td>
                    <td>Uncleared amount(Ksh)</td>
                    <td>Land Price (Ksh)</td>
                    <td>Change Ownership</td>
                </tr>
                <tr>
                    {% for land in lands_bought %}
                        <td>{{ land.land.title_deed_no }}</td>
                        <td>{{ land.land.approximate_size }}</td>
                        <td>{{ land.deposit_amount }}</td>
                        <td>{{ profile.user.first_name }}&nbsp;{{ profile.user.last_name }}</td>
                        <td>{{ profile.user.username }}</td>
                        <td>{{ land.date_deposited }}</td>
                        <td>{{ land.uncleared_amount }}</td>
                        <td>{{ land.land.sale_price }}</td>
                        <td><a href="{% url 'land:transfer_land' pk=land.pk %}">Change ownership</a></td>
                    {% endfor %}
                </tr>
            </table>
        {% else %}

            <div class="alert alert-info" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4></h4><strong>No lands bought yet.!</strong></div>
              </div>

        {% endif %}
        </div>
    {% endblock %}
{% else %}
<p>No land bought so far.</p>
{% endif %}

landsys/templates/land/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<style type="text/css">
    .div-login-form{
        margin-left: 50px !important;
        margin-right: 50px !important;
    }
</style>
{% block content %}
        <div class="row">
           <div class="col col-md-3"></div>
           <div class="jumbotron container">
            <div class="col-col-md-3"></div>
            <div class="div-login-form col col-md-6">
                <p><strong>Enter Your Credentials to login</strong></p>

                {% if message %}
                    <div class="alert alert-danger" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
             <div class="col-col-md-3" style="margin-left: 25px;">
                <form action="" method="post">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}" />
                    <input type="submit" value="login" class="col col-md-12 btn btn-success btn-raised">
                </form>
            <div>
            <span>
            &nbsp;&nbsp;Don't have account?<a href="{% url 'land:create_account' %}">Create Account</a>
            </span>
           </div>
        </div>
        </div>
    </div>
    </div>
{% endblock %}

landsys/templates/land/logout_then_login.html
{% extends 'base.html' %}
{% block content %}
    <div class="content">
    <div class="row">
        <div class="col col-md-6">
           <p> You are now logged out <a href="{% url 'land:login' %}"> login again</a> </p>
        </div>
    </div>

    </div>
{% endblock %}

landsys/templates/land/notification.html
{% extends 'base.html' %}

{% block notification %}
<div>
<ul>
    {% for note in notification %}


    {% endfor %}

</ul>
</div>
{% endblock %}

{% block content %}
  <ul>
 {% for n in all %}
     <div class="alert alert-primary" role="alert">
     {{ forloop.counter }}
     <li>Message From {{ n.sender }}
         <br><br>
     <p>{{ n.text }}</p>
     </li>
     </div>

 {% endfor %}
 </ul>
{% endblock %}

landsys/templates/land/register_land.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col col-md-6">
<form action="" method="post">
    {{ land_form | crispy }}
    {% csrf_token %}
    <input type="submit" value="Register Land" class="btn  btn-success btn-raised">
</form>
</div>

{% endblock %}

landsys/templates/land/register_land_success.html
{% extends 'base.html' %}

{% block content %}
    {% if error %}

        <div class="alert alert-danger">
        <p>{{ message }} </p>
        </div>

    {% else %}

        <div class="alert alert-success">
            <p>{{ message }} </p>
        </div>

    {% endif %}
{% endblock %}

landsys/templates/land/transfer_land.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
<div>

    <leged><strong>Land Transfer Information</strong></leged>
    <p>Transfer Land To (Buyer Account Name):<strong> {{ user.username }}</strong></p>
    <p>Buyer Fullname: <strong>{{ user.first_name  }}&nbsp;{{ user.last_name }}</strong></p>
    <p>This client has paid a deposit of <strong>(3/4)</strong> of total land sale of <strong>Ksh {{ land.deposit_amount }}</strong></p>
    <p>The uncleared amount is Ksh <strike><strong>{{ land.uncleared_amount }}</strong></strike></p>
    <p>Land Title Deed Number: {{ land.land.title_deed_no }}</p>

    <button class="btn btn-danger btn-raised">
        Continue to LandTransfer Ownership
    </button>

</div>
</div>

{% endblock %}

landsys/templates/land/transfer_payment.html
{% extends 'base.html' %}
{% block content %}
<div class="col col-md-12">
<form action="" method="post">
    {{ payment_form }}
    {% csrf_token %}
    <input type="submit" value="Submit Payment" class="btn btn-success btn-raised">
</form>
</div>
{% endblock %}