land/urls.py
from django.conf.urls import url
from land import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create-account/$', views.create_account, name='create_account'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^land/register/$', views.register_land, name='register_land'),
    url(r'^land/display/$', views.display_lands, name='display_lands'),
    url(r'^land/display/(?P<pk>[0-9])/$', views.land_detail, name='land_details'),
    url(r'^land/payment/(?P<pk>[0-9])/$', views.buy_land, name='buy_land'),
    url(r'^notifications/$', views.get_notification, name='notification'),
    url(r'^bought-lands/$', views.show_bought_land, name='lands_bought'),
    url(r'^transfer-land/(?P<pk>[0-9])/$', views.transfer_bought_land, name='transfer_land'),
    url(r'^transfer/(?P<land_id>[0-9])/$', views.transfer_land, name='transfer'),
    url(r'^my-land/$', views.my_land, name='my_land'),

]

landsys/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('land.urls', namespace='land'), ),
    url(r'^api/', include('payment.urls', namespace='api'), ),


]

admin.site.site_header = 'Nyeri Land System'

landsys/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} Nyeri Land Admistration System {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- my local css and bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %} " rel="stylesheet">
    {#    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>#}

    {#    css for material#}
    <link href="{% static 'material/css/bootstrap-material-design.css' %}" rel="stylesheet">
    <link href="{% static 'material/css/ripples.min.css' %}" rel="stylesheet">
    <!-- slider css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.bxslider.css' %}">
    <!--end of slider css -->


    <!--end of my local -->


    {#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>#}
    {#    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>#}
    <style type="text/css">
        /* Remove the navbar's default rounded borders and increase the bottom margin */
        .navbar {
            margin-bottom: 50px;
            border-radius: 0;
        }

        .custom {
            background-color: #ffffff;
            background-repeat: no-repeat;
            background-color: transparent;
        }

        /* Remove the jumbotron's default bottom margin */
        .jumbotron {
            margin-bottom: 0;

        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2!important;
            padding: 25px;
        }
    </style>
</head>
<body class="custom">
{#<div class="jumbotron">#}
{#    <div class="container text-center">#}
{#        <h1>Nyeri Land Admistration System  </h1>#}
{#    </div>#}
{#</div>#}

<nav class="navbar navbar-success">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Logo</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">

            <ul class="nav navbar-nav">

                <li class="active"><a href="{% url 'land:index' %}">Home</a></li>
                <li><a href="{% url 'land:register_land' %}">Register Land </a></li>
                <li><a href="{% url 'land:display_lands' %}">Lands On Sale</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Services
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">Nyeri Land Services</li>
                        <li><a href="{% url 'land:my_land' %}"> Transfer Land Ownership</a></li>


                    </ul>
                </li>

                {% if user.is_authenticated %}
                {% else %}
                    <li><a href="{% url 'land:create_account' %}">Create Account</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">My Profile
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Profile</li>
                            <li><a href="{% url 'land:lands_bought' %}">Lands Bought</a></li>
                            <li><a href="{% url 'land:my_land' %}"> My Lands</a></li>

                        </ul>
                    </li>

                    <li><a href="{% url 'land:notification' %}"><span class="glyphicon glyphicon-globe"></span>
                        Notifications</a></li>

                    <li><a href="#"><span class="glyphicon glyphicon-user"></span>
                    {{ request.user }}
                    <li><a href="{% url 'land:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
                    </li>
                {% else %}
                    <li><a href="{% url 'land:login' %}"><span class="glyphicon glyphicon-log-out"></span> Login</a>
                    </li>

                {% endif %}</a></li>

            </ul>
        </div>
    </div>
</nav>



    <div class="row">
        {% block left-side-bar %}
            <div class="col col-md-3">

            <div class="panel panel-success">
            <div class="panel-heading">
              <li>Menu</li>

            </div>
            <div class="panel-body" style="height: 1020px!important;">
                <ul>

               <li><a href="{% url 'land:register_land' %}">Register Land</a></li>
               <li><a href="{% url 'land:my_land' %}">My Lands</a></li>
               <li><a href="{% url 'land:display_lands' %}">Purchase Land</a></li>
               <li><a href="{% url 'land:notification' %}">My Account Notifications</a></li>



                 </ul>

            </div>
            <div class="panel-footer">

            </div>
             </div>


            </div>
        {% endblock %}
        <div class="content">
        <div class="col col-md-6">
            {% block content %}

            {% endblock %}
        </div>
        </div>
        {% block right-side-bar %}
            <div class="col col-md-3">
                <!--my right content here-->
            </div>
        {% endblock %}

    </div>
<footer class="container-fluid text-center">
    Nyeri Land Administration Copyright &copy;2016
</footer>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %} "></script>
<!--material js-->
<script src="{% static 'material/js/material.min.js' %}"></script>
<script src="{% static 'material/js/ripples.min.js' %}"></script>
<script src="{% static 'js/jquery.bxslider.min.js' %}"></script>
<script>
    $(function () {
        $.material.init();
    });
</script>


</body>